version: "3.9"

services:
  app:
    build: .
    container_name: ms-users
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: usersdb
      DB_USER: user
      DB_PASSWORD: root

  db:
    image: postgres:15
    container_name: ms-users-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
